#!/usr/bin/env bash
# ============================================================================
# Izy'Ah — full-stack backup (Postgres + Redis + MinIO + .env).
#
# Run from ~/izyah on the box that's CURRENTLY running the stack:
#   bash scripts/backup.sh
#
# Produces backups/izyah-backup-<timestamp>.tar.gz containing:
#   postgres.sql       pg_dumpall — every database + role (incl. Logto's, if
#                       account-linking is set up), so no schema/data is missed
#   redis-dump.rdb      Redis's own on-disk snapshot (forced fresh via SAVE)
#   minio-data.tar.gz   every uploaded photo/video/avatar, verbatim
#   env                 this box's .env — DB/MinIO passwords, SESSION_SECRET,
#                       OIDC/VAPID config
#
# The .env copy makes this archive as sensitive as your live secrets. Treat
# it like a password: scp it directly to wherever it's going, never email it,
# never commit it, delete local copies once you're done restoring elsewhere.
#
# Each run also prunes backups/ down to the BACKUP_KEEP (default 8) most
# recent archives, so running this on a schedule doesn't fill the disk.
#
# Use with scripts/restore.sh on the new box to move VPS providers without
# losing data. See that script's header for the full flow.
#
# Runs on a schedule automatically via the "backup" service in
# docker-compose.yml (scripts/backup-cron.js, node-cron) — no OS crontab
# needed. This script itself doesn't care who invokes it, by hand or by cron.
# ============================================================================
set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_DIR"

# Compose derives the project (used to find the already-running containers)
# from the current directory's basename unless told otherwise. Pin it so this
# still resolves correctly when run from the backup-cron sidecar, where the
# repo is bind-mounted at some unrelated path, not .../izyah.
export COMPOSE_PROJECT_NAME=izyah

log()  { printf '\n\033[36m==> %s\033[0m\n' "$*"; }
die()  { printf '\n\033[31m==> %s\033[0m\n' "$*" >&2; exit 1; }

[ -f .env ] || die ".env not found in $(pwd) — run this from the deployed box, in ~/izyah."

# Same compose invocation deploy.sh uses — falls back to the base file alone
# for a native/dev checkout with no prod overlay generated by setup.sh yet.
COMPOSE="docker compose -f docker-compose.yml -f docker-compose.prod.yml -f docker-compose.deploy.yml"
[ -f docker-compose.prod.yml ] || COMPOSE="docker compose -f docker-compose.yml"

read_env() { grep -E "^$1=" .env | head -n1 | cut -d= -f2- || true; }
POSTGRES_USER="$(read_env POSTGRES_USER)"
[ -n "$POSTGRES_USER" ] || die "POSTGRES_USER not set in .env"

cid() { $COMPOSE ps -q "$1"; }
[ -n "$(cid postgres)" ] || die "postgres isn't running — nothing to back up. Bring the stack up first."

STAMP="$(date -u +%Y%m%dT%H%M%SZ)"
WORKDIR="$(mktemp -d)"
trap 'rm -rf "$WORKDIR"' EXIT

log "Dumping Postgres (all databases + roles)"
$COMPOSE exec -T postgres pg_dumpall -U "$POSTGRES_USER" > "$WORKDIR/postgres.sql"

if [ -n "$(cid redis)" ]; then
  log "Snapshotting Redis"
  $COMPOSE exec -T redis redis-cli SAVE >/dev/null
  docker cp "$(cid redis):/data/dump.rdb" "$WORKDIR/redis-dump.rdb"
else
  log "Redis isn't running — skipping (analytics counters/cache, not core data)"
fi

if [ -n "$(cid minio)" ]; then
  log "Archiving MinIO object storage (uploaded media)"
  mkdir "$WORKDIR/minio-data"
  docker cp "$(cid minio):/data/." "$WORKDIR/minio-data/"
  tar czf "$WORKDIR/minio-data.tar.gz" -C "$WORKDIR" minio-data
  rm -rf "$WORKDIR/minio-data"
else
  log "MinIO isn't running — skipping (uploaded media will NOT be backed up!)"
fi

log "Copying .env"
cp .env "$WORKDIR/env"

mkdir -p backups
OUT="backups/izyah-backup-${STAMP}.tar.gz"
tar czf "$OUT" -C "$WORKDIR" .
chmod 600 "$OUT"
# Run from the backup-cron sidecar, this runs as root — match ownership to
# whoever owns .env on the HOST (the one thing here guaranteed to be a real
# bind mount, not baked into the image — see infra/backup/Dockerfile), so the
# archive is readable/scp-able without sudo. Harmless no-op when already the
# case (running directly on the host as your own user).
chown "$(stat -c '%u:%g' .env)" backups "$OUT" 2>/dev/null || true

log "Done: $OUT ($(du -h "$OUT" | cut -f1))"
echo "  This contains live secrets — copy it off this box securely, e.g. from your machine:"
echo "    scp <user>@<this-host>:$REPO_DIR/$OUT ."
echo "  then to the new VPS:"
echo "    scp izyah-backup-${STAMP}.tar.gz <user>@<new-host>:~/izyah/backups/"
echo "  ...and delete both copies once restored there."

# Retention — keep the KEEP most recent archives, delete the rest. Run on a
# schedule (the "backup" compose service), this is what stops backups/ from
# growing forever; override with BACKUP_KEEP if the default doesn't fit your
# schedule (e.g. more headroom for a more-frequent cadence).
KEEP="${BACKUP_KEEP:-8}"
mapfile -t existing < <(ls -1 backups/izyah-backup-*.tar.gz 2>/dev/null | sort)
total=${#existing[@]}
if [ "$total" -gt "$KEEP" ]; then
  stale=$((total - KEEP))
  log "Pruning ${stale} old backup(s), keeping the ${KEEP} most recent"
  for ((i = 0; i < stale; i++)); do
    echo "  rm ${existing[$i]}"
    rm -f "${existing[$i]}"
  done
fi
